base_config:
  data_name: census
  data_file: "datasets/census.csv"
  classes_file: "trained_model/census_encoder.yaml"
  label_col : "income"
  drop_col : ["fnlwgt"]
  val_ratio : 0.1
  dtmc_folder: "dtmc_results/census"
  mutation_bound: 0.2
DNN_config:
  model: DNN
  epochs: 20
  batch_size: 32
  lr: 0.0001
  weight_file: "trained_model/census_dnn.pt"
  device : cpu
svm_config:
  model: svm
  weight_file: "trained_model/census_svm.joblib"
  max_iter: 10000
rf_config:
  model: randomForest
  weight_file: "trained_model/census_rf.joblib"
  max_depth: 5