base_config:
  data_file: "datasets/census.csv"
  classes_file: "trained_model/census_encoder.yaml"
  label_col : "income"
  drop_col : ["fnlwgt"]
  val_ratio : 0.1
DNN_config:
  epochs: 20
  lr: 0.0001
  weight_file: "trained_model/dnn.pt"
  device : cuda